name: 🚀 Déploiement sur VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Récupérer le dépôt
        uses: actions/checkout@v3

      - name: 🔑 Installer sshpass
        run: |
          sudo apt-get install -y sshpass

      - name: 🚀 Déployer Backend
        if: contains(github.event.head_commit.modified, 'backend/')
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no alexandre@82.29.175.212 "cd /home/user/As-Gram/backend && git pull origin main && npm install && pm2 restart backend"
